name: Node CI tests

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Puppeteer action
      if: matrix.os == 'ubuntu-latest'
      uses: ianwalter/puppeteer@v2.0.0
      with:
        args: npm
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-${{ runner.OS }}-build-${{ hashFiles('package-lock.json') }}        
    - name: install + build
      run: npm ci
    - name: Cache H5P examples
      uses: actions/cache@v1
      with:
        path: test/data/hub-content
        key: h5p-hub-content-${{ hashFiles('test/data/content-type-cache/real-content-types.json') }}
    - name: Download content files from H5P Hub      
      run: npm run download:content
    - name: lint
      run: npm run lint
    - name: format
      run: npm run format:check
    - name: unit-tests
      run: npm run test
    - name: integration-tests
      run: npm run test:integration
    - name: player-e2e-test
      run: npm run test:e2e:player               
      env:
        CI: true
